#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    music-radar-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^music-radar\.ddev\.site$`)
      
      service: "music-radar-xhgui-80"
      tls: false
      # middlewares:
      #   - "music-radar-redirectHttps"
    music-radar-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^music-radar\.ddev\.site$`)
      
      service: "music-radar-web-80"
      tls: false
      # middlewares:
      #   - "music-radar-redirectHttps"
    music-radar-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^music-radar\.ddev\.site$`)
      
      service: "music-radar-web-8025"
      tls: false
      # middlewares:
      #   - "music-radar-redirectHttps"
    
    
    music-radar-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^music-radar\.ddev\.site$`)
      
      service: "music-radar-xhgui-80"
      
      tls: true
      
    
    
    music-radar-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^music-radar\.ddev\.site$`)
      
      service: "music-radar-web-80"
      
      tls: true
      
    music-radar-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^music-radar\.ddev\.site$`)
      
      service: "music-radar-web-8025"
      
      tls: true
      
    

  middlewares:
    music-radar-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    music-radar-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-music-radar-xhgui:80
        
    
    music-radar-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-music-radar-web:80
        
    music-radar-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-music-radar-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/music-radar.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/music-radar.key